/**
 * NonRegistLookupGrid.js
 * 청구요금 DataGrid정의
 *
 * @author 임상우
 * @date 2016. 8. 25. 오후 1:00:00
 * @version 1.0
 */
var NonRegistLookupGrid = (function($, Tango, _){
	
	var options = {} ;
	
	//BTS
	options.defineBtsDataGrid = {
		lesKndCd : 'T2',
		autoColumnIndex : true,
		rowindexColumnFromZero: false,
		defaultColumnMapping : {
			align : 'center',
			width : '90px',
			sorting : false
		},
		columnMapping: [
		                //{key: 'rnum', title: '순번', width: '40px', rowindexColumn: true},
						{key: 'hdofcOrgId', hidden : true},
						{key: 'teamOrgId', hidden : true},
						{key: 'trmsMtsoId', hidden : true},		                
						{key: 'fcltsDivNm', title:'시설구분'},					 
						{key: 'hdofcOrgNm',title:'본부', width : '180px'},					 
						{key: 'teamOrgNm',title:'팀', width : '180px'},							 
						{key: 'trmsMtsoNm',title:'전송실', width : '180px'},
						{key: 'srvcClVal',title:'사업구분'},					 
						{key: 'shrYn', title:'공용여부',width:100},				 
						{key: 'formDivVal', title:'형태',width:100},						 
						{key: 'erpNo', title:'ERP번호', width:100},
						{key: 'bmtsoMtsoNm', title:'기지국'},					 
						{key: 'leslNm', title:'회선명'},		
						{key: 'leslStatVal',title:'회선상태'},					 
						{key: 'leslNo', title:'회선번호'},		
		                {key: 'existYn', title: '회선존재여부', width : '120px'},			 
						{key: 'lineAppltDtm', title:'청약일'}, 
						{key: 'openDtm', title:'개통일'}, 
						{key: 'trmnDtm', title:'해지일'}, 
						{key: 'lastChgDate', title:'변경일'}, 
						{key: 'lesCommBizrNm', title:'사업자'},
						{key: 'lesCommBizrId', hidden : true},
						{key: 'areaCmtsoNm', title:'지역중심국명'}, 
						{key: 'areaCmtsoAcptYn', title:'지역중심국수용여부'},
						{key: 'selfNetObjYn', title:'자체망대상여부'},		 
						{key: 'selfNetCnstDtm', title:'구축시기'},				 
						{key: 'selfNetAcptYn', title:'자체망수용여부'},
						{key: 'umtsoNm', title:'상위국', width : '180px'},						 
						{key: 'lmtsoNm', title:'하위국', width : '180px'}, 
						{key: 'stdLesDistm', title:'구분'}, 
						{key: 'lesDistm', title:'거리'},
						{key: 'basUprc', title:'기본단가', align : 'right'}, 
						{key: 'mthUtilChag', title:'월이용료', align : 'right'}, 
						{key: 'devCost', title:'장치비', align : 'right'}, 
						{key: 'etcCost', title:'기타', align : 'right'},
						{key: 'feeSumrAmt', title:'요금계', align : 'right'}, 
						{key: 'drtCalcAplyDayCnt', title:'일할계산적용일수'},
						{key: 'drtCalcAmt', title:'일할계산액', align : 'right'}, 
						{key: 'rfndAmt', title:'환급', align : 'right'}, 
						{key: 'tmthSumrAmt', title:'당월계', align : 'right'}, 
						{key: 'atrnfYn', title:'자동이체여부'}, 
						{key: 'atrnfDiscAmt', title:'각종이체할인액', align : 'right'},
						{key: 'splyAmt', title:'공급가액', align : 'right'}, 
						{key: 'splyVat', title:'부가세', align : 'right'}, 
						{key: 'dmdAmt', title:'청구금액', align : 'right'}, 
						{key: 'leslCapaCd', title:'회선종류'}, 
						{key: 'chrYn', title:'과금여부'},					 
						{key: 'minUseDayCnt', title:'최소사용적용기간'}, 
						{key: 'minUseExprnDtm', title:'최소사용만료일'}, 
						{key: 'trmnPsblYn', title:'해지가능'},	 
						{key: 'lmtsoAddr', title:'하위국소재지', width : '180px'}, 
						//{key: 'lmtsoGuAddr', title:'시구군', width : '180px'},		 
						//{key: 'lmtsoDongAddr', title:'면동리', width : '180px'},		 
						{key: 'etcRmk', title:'비고'},				 
						{key: 'dmdYm', title:'청구연월'},	 
						{key: 'frstRegDate', title:'등록일자'},		 
						{key: 'frstRegUserId', title:'등록자ID'},
		    	        {key : 'dnrSystmNm', hidden : true},
		    	        {key : 'rmteSystmNm', hidden : true}
						]
	};
	
	//OPT
	options.defineOPTDataGrid = {
			lesKndCd : 'T1',
			autoColumnIndex : true,
			rowindexColumnFromZero: false,
			defaultColumnMapping : {
				align : 'center',
				width : '90px',
				sorting : false
			},
			columnMapping: [
			                //{key: 'rnum', title: '순번', width: '40px', rowindexColumn: true},
			                {key: 'fcltsDivNm', title: '시설구분'},
							{key: 'hdofcOrgId', hidden : true},
							{key: 'teamOrgId', hidden : true},
							{key: 'trmsMtsoId', hidden : true},
			                {key: 'hdofcOrgNm', title: '본부', width : '180px'},
			                {key: 'teamOrgNm', title: '팀', width : '180px'},
			                {key: 'trmsMtsoNm', title: '전송실', width : '180px'},
			                {key: 'leslNo', title: '회선번호'},
			                {key: 'existYn', title: '회선존재여부', width : '120px'},
			                {key: 'dnrSystmNm', title: 'DONOR시스템명', width : '180px'},
			                {key: 'rmteSystmNm', title: 'REMOTE시스템명', width : '180px'},
			                {key: 'leslStatVal', title: '회선상태'},
			                {key: 'lesDistm', title: '거리'},
			                {key: 'coreCnt', title: '코아수'},
			                {key: 'lineAppltDtm', title: '청약일'},
			                {key: 'openDtm', title: '개통일'},
			                {key: 'trmnDtm', title: '해지일'},
			                {key: 'lastChgDate', title: '변경일'},
			                {key: 'basUprc', title: '기본단가', align : 'right'},
			                {key: 'mthUtilChag', title: '월이용료', align : 'right'},
			                {key: 'tlplChag', title: '전주료', align : 'right'},
			                {key: 'etcCost', title: '기타', align : 'right'},
			                {key: 'feeSumrAmt', title: '요금계', align : 'right'},
			                {key: 'drtCalcAplyDayCnt', title: '일할계산적용일'},
			                {key: 'drtCalcAmt', title: '일할계산액', align : 'right'},
			                {key: 'rfndAmt', title: '환급', align : 'right'},
			                {key: 'tmthSumrAmt', title: '당월계', align : 'right'},
			                {key: 'atrnfYn', title: '자동이체여부'},
			                {key: 'atrnfDiscAmt', title: '자동이체금액', align : 'right'},
			                {key: 'splyAmt', title: '공급가액', align : 'right'},
			                {key: 'splyVat', title: '부가세', align : 'right'},
			                {key: 'dmdAmt', title: '청구금액', align : 'right'},
			                {key: 'lesCommBizrNm', title: '사업자'},
			                {key: 'lesCommBizrId', hidden : true},
			                {key: 'chrYn', title: '과금여부'},
			                {key: 'minUseDayCnt', title: '최소사용기간'},
			                {key: 'minUse_exprnDtm', title: '최소사용만료일'},
			                {key: 'trmnPsblYn', title: '해지가능여부'},
			                {key: 'umtsoAddr', title: '상위국주소', width : '180px'},
			                //{key: 'umtsoGuAddr', title: '상위국시구군', width : '180px'},
			                //{key: 'umtsoDongAddr', title: '상위국면동리', width : '180px'},
			                {key: 'lmtsoAddr', title: '하위국주소', width : '180px'},
			                //{key: 'lmtsoGuAddr', title: '하위국시구군', width : '180px'},
			                //{key: 'lmtsoDongAddr', title: '하위국면동리', width : '180px'},
			                {key: 'etcRmk', title: '비고'},
			                {key: 'dmdYm', title: '청구연월'},
			                {key: 'frstRegDate', title: '등록일자', width: '140px'},
			                {key: 'frstRegUserId', title: '등록자ID', width: '110px'}]
	};
	
	//WiFi Grid
	options.defineWIFIDataGrid = {
			lesKndCd : 'T4',
			autoColumnIndex : true,
			rowindexColumnFromZero: false,
			defaultColumnMapping : {
				align : 'center',
				width : '90px',
				sorting : false
			},
			columnMapping: [
			                //{key: 'rnum', title: '순번', width: '40px', rowindexColumn: true},
							{key: 'fcltsDivNm', title:'시설구분'},
							{key: 'hdofcOrgId', hidden : true},
							{key: 'teamOrgId', hidden : true},
							{key: 'trmsMtsoId', hidden : true},
							{key: 'hdofcOrgNm',title:'본부', width : '180px'},
							{key: 'teamOrgNm',title:'팀', width : '180px'},
							{key: 'trmsMtsoNm',title:'전송실', width : '180px'},
							{key: 'srvcClVal',title:'사업구분'},
							{key: 'afcpyNm',title:'제휴사', width : '180px'},
							{key: 'fnchNm',title:'가맹점', width : '180px'},
							{key: 'leslStatVal',title:'회선상태'},
							{key: 'leslNo',title:'회선번호'},
			                {key: 'existYn', title: '회선존재여부', width : '120px'},
							{key: 'lineAppltDtm', title:'청약일'},
							{key: 'openDtm', title:'개통일'},
							{key: 'trmnDtm', title:'해지일'},
							{key: 'lastChgDate', title:'변경일'},
							{key: 'lesCommBizrNm', title:'사업자'},
							{key: 'lesCommBizrId', hidden : true},
							{key: 'areaCmtsoNm', title:'지역중심국명'},
							{key: 'umtsoNm', title:'관할국(상위국)', width : '180px'},
							{key: 'lmtsoNm', title:'관할국(하위국)', width : '180px'},
							{key: 'stdLesDistm', title:'구분'},
							{key: 'lesDistm', title:'거리'},
							{key: 'basUprc', title:'기본단가', align : 'right'},
							{key: 'mthUtilChag', title:'월이용료', align : 'right'},
							{key: 'devCost', title:'장치비', align : 'right'},
							{key: 'etcCost', title:'기타', align : 'right'},
							{key: 'feeSumrAmt', title:'요금계', align : 'right'},
							{key: 'drtCalcAplyDayCnt', title:'일할계산적용일수'},
							{key: 'drtCalcAmt', title:'일할계산액', align : 'right'},
							{key: 'rfndAmt', title:'환급금액', align : 'right'},	
							{key: 'tmthSumrAmt', title:'당월계', align : 'right'},
							{key: 'atrnfYn', title:'자동이체여부', align : 'right'},
							{key: 'atrnfDiscAmt', title:'자동이체할인액', align : 'right'},
							{key: 'splyAmt', title:'공급가액', align : 'right'},
							{key: 'splyVat', title:'부가세', align : 'right'},
							{key: 'dmdAmt', title:'청구금액', align : 'right'},	
							{key: 'leslCapaCd', title:'회선종류'},
							{key: 'AP_CNT', title:'AP수량'},				
							{key: 'lmtsoAddr', title:'하위국소재지', width : '180px'},	
							//{key: 'lmtsoGuAddr', title:'시구군', width : '180px'},
							//{key: 'lmtsoDongAddr', title:'면동리', width : '180px'},
							{key: 'etcRmk', title:'비고'},
							{key: 'termlEqpNm', title:'종단장치'},
							{key: 'frstRegDate', title:'등록일자'},
							{key: 'frstRegUserId', title:'등록자ID', width:110}]
	};
	
	//B2B Grid
	options.defineB2BDataGrid = {
			lesKndCd : 'T5',
			autoColumnIndex : true,
			rowindexColumnFromZero: false,
			defaultColumnMapping : {
				align : 'center',
				width : '90px',
				sorting : false
			},
			columnMapping: [
			                //{key: 'rnum', title: '순번', width: '40px', rowindexColumn: true},
							{key: 'hdofcOrgNm',title:'본부', width : '180px'},
							{key: 'teamOrgNm',title:'팀', width : '180px'},
							{key: 'hdofcOrgId', hidden : true},
							{key: 'teamOrgId', hidden : true},
							{key: 'trmsMtsoId', hidden : true},							
							{key: 'lesCommBizrNm', title:'사업자'},
							{key: 'lesCommBizrId', hidden : true},
							{key: 'leslNo',title:'회선번호'},				
							{key: 'umtsoNm', title:'상위국명', width : '180px'},
							{key: 'lmtsoNm', title:'하위국명', width : '180px'},
							{key: 'umtsoAddr', title:'상위국주소', width:200},
							{key: 'lmtsoAddr', title:'하위국주소', width:200},
							{key: 'leslCapaCd', title:'회선종류'},
							{key: 'leslStatVal',title:'회선상태'},
							{key: 'openDtm', title:'과금개시일'},
							{key: 'trmnDtm', title:'해지일'},
							{key: 'splyAmt', title:'공급가액', align : 'right'},
							{key: 'sktLineId', title:'SKT2 회선번호', width:120},
							{key: 'custNm', title:'고객명', width:120},
							{key: 'frstRegDate', title:'등록일자'},
							{key: 'frstRegUserId', title:'등록자ID'}]
	};
	
	//HFC중계기 Grid
	options.defineHFCDataGrid = {
		lesKndCd : 'T6',
		autoColumnIndex : true,
		rowindexColumnFromZero: false,
		defaultColumnMapping : {
			align : 'center',
			width : '90px',
			sorting : false
		},
		columnMapping: [
		                //{key: 'rnum', title: '순번', width: '40px', rowindexColumn: true},
		                {key: 'fcltsDivNm', title: '시설구분'},
						{key: 'hdofcOrgId', hidden : true},
						{key: 'teamOrgId', hidden : true},
						{key: 'trmsMtsoId', hidden : true},
		                {key: 'hdofcOrgNm', title: '본부', width : '180px'},
		                {key: 'teamOrgNm', title: '팀', width : '180px'},
		                {key: 'trmsMtsoNm', title: '전송실', width : '180px'},
		                {key: 'leslNo', title: '회선번호'},
		                {key: 'dnrSystmNm', title: 'DONOR시스템명', width : '180px'},
		                {key: 'rmteSystmNm', title: 'REMOTE시스템명', width : '180px'},
		                {key: 'leslStatVal', title: '회선상태'},
		                {key: 'lesDistm', title: '거리'},
		                {key: 'coreCnt', title: '코아수'},
		                {key: 'lineAppltDtm', title: '청약일'},
		                {key: 'openDtm', title: '개통일'},
		                {key: 'trmnDtm', title: '해지일'},
		                {key: 'lastChgDate', title: '변경일'},
		                {key: 'basUprc', title: '기본단가', align : 'right'},
		                {key: 'mthUtilChag', title: '월이용료', align : 'right'},
		                {key: 'tlplChag', title: '전주료', align : 'right'},
		                {key: 'etcCost', title: '기타', align : 'right'},
		                {key: 'feeSumrAmt', title: '요금계', align : 'right'},
		                {key: 'drtCalcAplyDayCnt', title: '일할계산적용일'},
		                {key: 'drtCalcAmt', title: '일할계산액', align : 'right'},
		                {key: 'rfndAmt', title: '환급', align : 'right'},
		                {key: 'tmthSumrAmt', title: '당월계', align : 'right'},
		                {key: 'atrnfYn', title: '자동이체여부'},
		                {key: 'atrnfDiscAmt', title: '자동이체금액', align : 'right'},
		                {key: 'splyAmt', title: '공급가액', align : 'right'},
		                {key: 'splyVat', title: '부가세', align : 'right'},
		                {key: 'dmdAmt', title: '청구금액', align : 'right'},
		                {key: 'lesCommBizrNm', title: '사업자'},
		                {key: 'lesCommBizrId', hidden : true},
		                {key: 'chrYn', title: '과금여부'},
		                {key: 'minUseDayCnt', title: '최소사용기간'},
		                {key: 'minUse_exprnDtm', title: '최소사용만료일'},
		                {key: 'trmnPsblYn', title: '해지가능여부'},
		                {key: 'umtsoAddr', title: '상위국주소', width : '180px'},
		                //{key: 'umtsoGuAddr', title: '상위국시구군', width : '180px'},
		                //{key: 'umtsoDongAddr', title: '상위국면동리', width : '180px'},
		                {key: 'lmtsoAddr', title: '하위국주소', width : '180px'},
		                //{key: 'lmtsoGuAddr', title: '하위국시구군', width : '180px'},
		                //{key: 'lmtsoDongAddr', title: '하위국면동리', width : '180px'},
		                {key: 'etcRmk', title: '비고'},
		                {key: 'dmdYm', title: '청구연월'},
		                {key: 'frstRegDate', title: '등록일자', width: '140px'},
		                {key: 'frstRegUserId', title: '등록자ID', width: '110px'}]
	};

	return options;
	
}(jQuery, Tango, _));


